name: Github Pages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Installing my packages
        run: npm ci

      - name: Build Blog
        run: npm run build && touch ./out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: out
          branch: gh_pages
